# Generated by Django 4.2.1 on 2024-05-22 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('emp_phone', models.CharField(max_length=10, unique=True)),
                ('emp_dob', models.DateField()),
                ('emp_gender', models.CharField(max_length=10)),
                ('emp_type', models.CharField(max_length=50)),
                ('emp_profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
