# Generated by Django 4.0.6 on 2023-06-28 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import patient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FT',
            fields=[
                ('patient_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('is_new_patient', models.BooleanField(default=True)),
                ('patient_token', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatientPrimaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=16, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_dob', models.DateField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=17)),
                ('guardian_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=16)),
                ('report_file', models.FileField(upload_to=patient.models.get_report_upload_path)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('pulse', models.CharField(max_length=100)),
                ('bp', models.CharField(max_length=100)),
                ('is_diabetic', models.BooleanField(default=False)),
                ('diabetic_level', models.CharField(blank=True, max_length=100, null=True)),
                ('phi', models.TextField(max_length=1000)),
                ('pov', models.TextField(max_length=300)),
                ('remarks', models.TextField(max_length=1000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprimarydata')),
            ],
        ),
    ]
