# Generated by Django 4.0.6 on 2023-06-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ft',
            name='patient_token',
            field=models.IntegerField(default=1),
        ),
    ]
