# Generated by Django 4.2.2 on 2023-07-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='appointment_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_token',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='today_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
