# Generated by Django 4.2.2 on 2023-07-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_visit_appointment_id_alter_visit_doctor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDD',
            fields=[
                ('appointment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patient.visit')),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('pulse', models.CharField(max_length=100)),
                ('bp', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('is_diabetic', models.BooleanField(default=False)),
                ('diabetic_level', models.CharField(blank=True, default=None, max_length=100)),
                ('phi', models.TextField(max_length=1000)),
                ('pov', models.TextField(max_length=300)),
                ('remarks', models.TextField(max_length=1000)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprimarydata')),
            ],
        ),
    ]
