# Generated by Django 4.2.2 on 2023-07-16 14:30

from django.db import migrations, models
import django.db.models.deletion
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTestResult',
            fields=[
                ('appointment_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('report_file', models.ImageField(upload_to=patient.models.get_report_upload_path)),
                ('uploaded_datetime', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprimarydata')),
            ],
        ),
    ]
