# Generated by Django 4.2.1 on 2024-05-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_testform'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTest',
            fields=[
                ('appointment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patient.visit')),
                ('date_prescribed', models.DateField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprimarydata')),
                ('tests', models.ManyToManyField(to='patient.testform')),
            ],
        ),
    ]
