# Generated by Django 4.2.1 on 2024-05-25 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patienttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='test_reports/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('patient_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='patient.patienttest')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.testform')),
            ],
        ),
    ]
