# Generated by Django 4.2.1 on 2024-05-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dosage_strength',
            field=models.TextField(blank=True),
        ),
    ]
