# Generated by Django 4.2.1 on 2024-05-25 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_medicine_dosage_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPrescription',
            fields=[
                ('appointment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patient.visit')),
                ('date_prescribed', models.DateField(auto_now_add=True)),
                ('chief_complaints', models.CharField(max_length=255)),
                ('clinical_findings', models.TextField()),
                ('investigations', models.TextField()),
                ('diagnosis', models.TextField()),
                ('procedures_conducted', models.CharField(max_length=255)),
                ('advice_given', models.TextField()),
                ('next_visit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('feeding_rule', models.CharField(max_length=100)),
                ('feeding_time', models.CharField(max_length=100)),
                ('feeding_days', models.CharField(max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprescription')),
            ],
        ),
        migrations.AddField(
            model_name='patientprescription',
            name='medicines',
            field=models.ManyToManyField(through='patient.PrescribedMedicine', to='patient.medicine'),
        ),
        migrations.AddField(
            model_name='patientprescription',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprimarydata'),
        ),
    ]
