# Generated by Django 4.2.1 on 2024-05-25 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_patientprescription_prescribedmedicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedmedicine',
            name='date_prescribed',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
